# -*- coding: utf-8 -*-
"""Heart Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14h4UVDd_Sm3L2IxdPk571X6Edf5PBTNq

###Cardiac Heart dieseases
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

"""Data Preprocessing"""

heart=pd.read_csv('heart.csv')

heart.head()

heart.shape

heart.isna().sum()

X=heart.drop(columns=['target'])
Y=heart['target']

X.shape

Y.shape

heart.dtypes

heart['oldpeak'] = heart['oldpeak'].astype(int)

X.head()

"""Split the data into test and train"""

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2) #splitting the model into 80:20 ratio

X_train.shape

X_test.shape

"""KNN model"""

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train, Y_train)

model.predict(X_test)

Y_test


import pickle

# Define the filename
filename = 'heart.pkl'

# Save the model
with open(filename, 'wb') as file:
    pickle.dump(model, file)

print(f'Model saved to {filename}')